name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    name: Run Tests
    env:
      TESTING: true
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9.12'
          # Change to your desired Python version

      - name: Setup Python Virtual Environment
        run: python -m venv venv

      - name: Install Dependencies
        run: venv/bin/pip install -r requirements.txt

      - name: Clear Database
        run: TESTING=true python3 -c "from app import mydb, TimeLinePost; mydb.connect(reuse_if_open=True); TimeLinePost.delete().execute(); print('Database cleared successfully')"
      - name: Run Tests
        run: ./run_test.sh
